/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphiquePackage;

import SourcePackage.Main;
import SourcePackage.ThreadReceive;
import SourcePackage.User;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.HashMap;

import static java.lang.Thread.sleep;

/**
 *
 * @author elyes
 */

	

public class FichAccueil extends javax.swing.JFrame {

    /**     * Creates new form FichMenu
     */
	
	private static int i = 0;
    private FichMenu menu;
    
    public FichAccueil() {
        
    	
       initComponents();

    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Pseudo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BIENVENUE");

        Pseudo.setText("Entrez pseudo");
        Pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PseudoActionPerformed(evt);
            }
        });

        jButton1.setText("Se connecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(Pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(314, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PseudoActionPerformed
     
    }//GEN-LAST:event_PseudoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           String a = Pseudo.getText();
           
           Main.user.sendMessageUDP("quiti",Main.user.getPort());
           ThreadReceive threadReceive = new ThreadReceive("quiti",Main.user);
           threadReceive.start();
           System.out.println("J'ai lancé le thread");
           

        	   	System.out.println("hash dans le while");
           	System.out.println(Main.user.getListUser().toString());
	          
           	if(i < 1) {
	           	try {
					sleep(3000);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
           	}
           i++;
           if(Main.user.getListUser().containsKey(a))
	    	   		System.out.println("pareil gros");
	       else if (!Main.user.getListUser().containsKey(a)){
	   	   		threadReceive = new ThreadReceive("thread",Main.user);
	   	   		Main.user.removeUserList("quiti");
	   	           System.out.println("hash actuelle");
	   	           System.out.println(Main.user.getListUser().toString());
	   	   		Main.user.setPseudo(a);
	   	   		Main.user.startThread();
	   	   		menu = new FichMenu(this, false);
	           	this.setVisible(false);
	           	menu.setVisible(true);
	           	Main.setFichMenu(menu); 
                        System.out.println("POOOOOOORT : >>>>>>>" + Main.user.getPort());
	       }
	       else if(!Main.user.getListUser().toString().contains("quiti")) {
	    	   		System.out.println("mmmmh");
	       }
           
            
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

        
    
    /**
     * @param args the command line arguments
     */

    public String getPseudo(){
        return Pseudo.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pseudo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
